### ISSUE TITLE
Google Home Commands Not Working

### ISSUE THREAD

**Issue by regicsolutions** [DoctorMcKay/HSPI_LiftMasterMyQ#3]
When you have two garage doors setup in myq and say Open Garage Door One, Google says that mode isn't available for Garage Door One. same for Garage Door two.

Whats weird is when i say Close Garage Door One it works. Says Locking the Garage Door One.

I enabled voice control and set the voice command to be Garage Door One and Garage Door two, they both work directly through HomeSeer though.

**Comment by DoctorMcKay** [comment]
On the "Status Graphics" tab in the device page, make sure that Close has Control Use set to "Door Lock".

If it is, then this is a problem with HS3.
